### ISSUE TITLE
Outlined text in Figma doesn't translate to AE

### ISSUE THREAD

**Issue by mmarol** [google/sketch2ae#22]
**Describe the bug**
If you try to send outlined text in Figma to Ae, only the first letter gets sent.

**To Reproduce**
1. Type some text in a frame in Figma
2. Convert the text to outlines
3. Select the outlined text
4. Send to Ae through the plugin
5. See error

**Expected behavior**
All the letters should be sent to Ae as multiple paths within a single shape, but instead only the first letter gets sent.

**Screenshots**
![Screen Shot 2020-10-05 at 10 36 56](https://user-images.githubusercontent.com/6997772/95093476-d3cbc380-06f6-11eb-98ad-f2a06d40fff6.png)
![Screen Shot 2020-10-05 at 10 37 28](https://user-images.githubusercontent.com/6997772/95093477-d4645a00-06f6-11eb-8701-b0f05c67be22.png)

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.7
 - Figma Desktop App release 88 - Build 1
 - After effects Version 17.1.4 (Build 37)

**Additional context**
This happens when you create multiple separate shapes and combine then using the Flatten Selection (Cmd + e) command in Figma as well. It does not happen when you use the pen tool to create distinct shapes within a single use of the pen tool.

**Comment by adamplouff** [comment]
This was a recently fixed in 0.7.5a. Figma is able to nest multiple paths into a single shape (unlike Ae) so it was missed. Download the newest Figma plugin and try again: https://aeux.io/guide/download.html

**Comment by mmarol** [comment]
Thank you!
