### ISSUE TITLE
AEUX 0.7.6 fail to export to AE

### ISSUE THREAD

**Issue by ash-sharifi** [google/sketch2ae#33]
I have updated my After Effects to latest v17.5.1 and the plugin doesn't connect to AE anymore. 
Screenshot : https://i.ibb.co/wgG4gxn/Screenshot-2020-11-30-at-10-23-33.png

**Comment by adamplouff** [comment]
Often, a system restart will clear that up. If not, try uninstalling then reinstalling Ae. Any luck?
