### ISSUE TITLE
Unable to call "addFolder" because of parameter 1. Value is undefined.

### ISSUE THREAD

**Issue by suhaibsaqib** [google/sketch2ae#39]
**Describe the bug**
Hi,
Thanks for creating this amazing utility, it really speeds up my workflow.
Unfortunately, whenever I try to transfer anything other than a simple shape from either sketch or figma I get this error:
Error: After Effects error: Unable to call “addFolder” because of parameter 1. Value is undefined.
Error on line: 829

I have tried restarting my computer, restarting AE, and flattening shapes, but the moment they are in a group it throws this error. So I haven't been able to preserve alignment and relationships between different elements. 

**Expected behavior**
Transfer assets and create heirarchy of compositions based on grouping while preserving relationships between different elements.

**Screenshots**
![Screen Shot 2020-12-15 at 12 33 08 AM](https://user-images.githubusercontent.com/5430678/102192321-7929b300-3e6f-11eb-979a-c669a663c786.png)

**Desktop (please complete the following information):**
 - OS: Mac OS, Catalina 10.15.7 
 - AE 2020 17.5.1 (Build 47)

**Comment by adamplouff** [comment]
This should now be fixed in [v0.7.8](https://github.com/google/sketch2ae/releases/tag/v0.7.8). Let me know if the problem persists.

**Comment by suhaibsaqib** [comment]
Thanks, Adam!
It works now, phew!
I appreciate all the work you've been doing on this utility, moreso after having to manually align so many elements in AE.
