### ISSUE TITLE
ReferenceError: importVersion is undefinied / Error on line: 1485 

### ISSUE THREAD

**Issue by EffDoubleJu** [google/sketch2ae#40]
I cannot send my stuff from Sketch to AE. I tried a basic shape, a rectangle with a grey fill color.

The error message warns:  **ReferenceError: importVersion is undefinied / Error on line: 1485** 

I updated Mac OS Big Sur to the lastest version that came out 12-15-20 (11.0.1 to 11.1.)
AE: 17.5.1
Sketch: 70.2
AEUX: 0.7.8.

Any ideas?

**Comment by adamplouff** [comment]
I missed scoping that variable in Ae a couple versions back. Download 0.7.7+ and you wont see that again. 

Ironically, that was supposed to simply alert users to download the updated Ae panel when Sketch/Figma updated and required an Ae update. 😂

**Comment by EffDoubleJu** [comment]
Hi, thanks for the fast feedback. It has been much easier: I forgot to update the zxp extension to 0.7.8. in AE. Sorry, my fault. Now it works.
