### ISSUE TITLE
CC2020 is not currently supported,Looking forward to the update.

### ISSUE THREAD

**Issue by LRachel0713** [google/sketch2ae#42]

**Comment by adamplouff** [comment]
CC2020 is fully supported. If you are seeing an error in [ZXP Installer](https://aescripts.com/learn/zxp-installer/) about no supported versions, just ignore it. This is a harmless (but annoying bug) in the way Adobe app versions are identified. 

If you still have trouble, do a [manual install](https://aeux.io/guide/install.html#after-effects).
