### ISSUE TITLE
Figma plugin not working

### ISSUE THREAD

**Issue by haileyylum** [google/sketch2ae#43]
Hi, I just get started on this plugin but unfortunately when I tried to import the plugin to Figma, it return a typescript error and I have followed the read.me instruction run in VS code, the terminal console return the error messages. Please let me know if I have missed anything.

Thanks!

`[20:00:04] Starting compilation in watch mode...

code.ts:8:14 - error TS2304: Cannot find name 'SceneNode'.

8 const nodes: SceneNode[] = [];
               ~~~~~~~~~

code.ts:10:16 - error TS2304: Cannot find name 'figma'.

10   const rect = figma.createRectangle();
                  ~~~~~

code.ts:13:3 - error TS2304: Cannot find name 'figma'.

13   figma.currentPage.appendChild(rect);
     ~~~~~

code.ts:16:1 - error TS2304: Cannot find name 'figma'.

16 figma.currentPage.selection = nodes;
   ~~~~~

code.ts:17:1 - error TS2304: Cannot find name 'figma'.

17 figma.viewport.scrollAndZoomIntoView(nodes);
   ~~~~~

code.ts:21:1 - error TS2304: Cannot find name 'figma'.

21 figma.closePlugin();
   ~~~~~

[20:00:05] Found 6 errors. Watching for file changes.

                               `

**Comment by adamplouff** [comment]
Sorry for the trouble. You should not have to be using VS Code at all. Everything runs within the Figma interface. Did you install it following the [Non-Googlers installation](https://aeux.io/guide/install.html#figma)?
