### ISSUE TITLE
It doesn't work. (Mac OS 11.1+Sketch70.3+AE2020-17.5.0) AE-ReferenceError

### ISSUE THREAD

**Issue by hugo-van** [google/sketch2ae#45]
After click the "send the selection to Ae" from sketch. it doesn't work and show this: ReferenceError: ”importVersion” Error on line:1485

 - OS: [Mac OS]
 - Version [11.1]

-Sketch70.3
-AE2020-17.5.0

![截屏2021-01-26 上午11 46 39](https://user-images.githubusercontent.com/78006841/105798454-23e3d400-5fcd-11eb-865e-37ca8e67cdf3.png)

**Comment by adamplouff** [comment]
[Download](https://aeux.io/guide/download.html) the updated version of the Ae panel from aeux.io and you will be set. This was bug in one of the previous versions but 0.7.8+ should work fine.
