### ISSUE TITLE
Figma2AE: Exported frame selection is created at 1/2 resolution 

### ISSUE THREAD

**Issue by robertobrambila** [google/sketch2ae#46]
**Describe the bug**
When exporting a Frame from Figma to AE, the created composition comes in at 1/2 the size. E.g. a 1920x1080 frame comes in as a 960x540 composition in After Effects.

**Expected behavior**
A Figma frame of 1920x1080 should be created as an AE composition of 1920x1080 resolution.

**Workaround**
I've been manually scaling or creating my frames in Figma to 1/2 size before exporting to AE.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 0.7.8

**Comment by adamplouff** [comment]
Thats a weird one. AEUX should only be be able to create the size of the frame as its minimum size when the comp multiplier is set to 1x, never create one smaller than the Figma source. Double check Figma's native size but if that's ok, try setting the [new comp multiplier](https://aeux.io/guide/ae-options.html#new-comp) in the Ae panel to 2x.

**Comment by robertobrambila** [comment]
Thanks for multiplier tip that saves me from having to manually scale down or design at 1/2 in Figma (I'm in AE 2020 if that helps at all).

**Comment by Zhao-Joe** [comment]
but i couldn't use AEUX in Figma. it always show a error (like couldn't connect with ae). do you use it now in 2021?
