### ISSUE TITLE
Font names fail to match from Figma to AE

### ISSUE THREAD

**Issue by qinyiyao** [google/sketch2ae#61]
Many font names will fail to match in AE and fall back to Myriad Pro. This is due to the simple font name transformation rules used in the plugin. 

To start, many fonts **do not** have PostScript names that perfectly match the their display names. “Arial Regular” on macOS has a PostScript name of `ArialMT`. (At least mine.) Note that: first, the `MT` could be the foundry name (Monotype) for disambiguation; second, the “Regular” style name is sometimes omitted since it’s the default weight. Same applies to “IBM Plex Sans Regular” `IBMPlexSans` or “Source Sans Pro Italic” `SourceSansPro-It`.

In addition, there may or may not be issues with other types of characters (:–—&()+", etc.) or non-latin-based characters. 

**The ideal solution would be to actually pass the source PostScript name from Figma to AE.**

I made a tiny fix #60 to deal with font names with multiple spaces in them, but that’s a different problem and it’s still a terrible solution for font name referencing.

**To Reproduce**
1. In Figma, create a text layer and choose Arial.
2. Send to AE.
3. Font family will revert back to the default Myriad Pro.

Sketch plugin not tested.

You can also check the correct PostScript name in AE by opening up any expression field, and do the following:

<img width="329" alt="Screen Shot 2021-04-20 at 4 31 26 AM" src="https://user-images.githubusercontent.com/6311717/115388887-497a1700-a191-11eb-93d0-c57d214cc010.png">

<img width="392" alt="Screen Shot 2021-04-20 at 4 40 03 AM" src="https://user-images.githubusercontent.com/6311717/115389890-7aa71700-a192-11eb-87ae-0ab375735369.png">

This will prompt you to select a font with 2 dropdowns. Confirming it will put a PostScript name in string inside the expression field.

**Comment by adamplouff** [comment]
Great catch on that. Approved the PR

**Comment by kompanets** [comment]
@qinyiyao 
Hey, I`m facing the same issue. I carefully read your text but I'm a designer, now a programmer, and I can't get it. 
Can you explain to Gramma step by step what I need to do?

**Comment by qinyiyao** [comment]
> @qinyiyao
> Hey, I`m facing the same issue. I carefully read your text but I'm a designer, now a programmer, and I can't get it.
> Can you explain to Gramma step by step what I need to do?

Inspect the font name in macOS Font Book:

<img width="250" alt="CleanShot 2023-04-08 at 19 19 04@2x" src="https://user-images.githubusercontent.com/6311717/230750831-89fa52c8-d4f8-41c9-8334-2645ba0ad3b2.png">

Family Name + `-` + Style Name with spaces removed `Arial-Bold` does not necessarily equal the actual PostScript Name `Arial-BoldMT` which is how AE uniquely identifies fonts.

**Comment by kompanets** [comment]
@qinyiyao Thank you a lot, your response really helped me! I have just renamed Postscript and now AE defines a font correctly! 
It seems, now, I have overwhelming work to do renaming most of the fonts in my system
